### ISSUE TITLE
Add `design capacity` and `full charge capacity` sensor

### ISSUE THREAD

**Issue by syssi** [syssi/esphome-ogt-bms#11]
@SigLinJo I've implemented two new sensors:

```
    design_capacity:
      name: "${name} design capacity"
    full_charge_capacity:
      name: "${name} full charge capacity"
```

Could you add these sensors to your YAML configuration and give it a try? A `VERY_VERBOSE` ESPHome log would be welcome. :-)
